name: Deploy Backend to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSH Key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.DO_SSH_KEY }}

      - name: Deploy to DigitalOcean
        env:
          DO_HOST: ${{ secrets.DO_HOST }}
          DO_USER: ${{ secrets.DO_USER }}
        run: |
          ssh -o StrictHostKeyChecking=no $DO_USER@$DO_HOST << 'EOF'
            # Navigate to your backend directory on the droplet
            cd /home/$DO_USER/backend  # Assuming the 'backend' folder is inside the user's home directory

            # Pull the latest changes from the GitHub repo
            git pull origin main

            # Install dependencies and restart the Node.js server (assuming PM2 is used)
            npm install
            pm2 restart all
            EOF